### ISSUE TITLE
[📍 Task Card - Client] 법안 발의문 상세 페이지 관련 컴포넌트 구현 (3) - 투표

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#16]
### **ISSUE**

- Type: `Feature`, `Client` 
- Detail: 법안 발의문 상세 페이지 관련 컴포넌트 구현

### **TODO**

- [x] 법안 발의문 찬반투표 구현
- [x] 투표 취소하기 구현
- [x] 투표 결과바꾸기 구현
