### ISSUE TITLE
[📍 Task Card - Server] 법안 발의문 통계 기능 구현 (1)

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#17]
### **ISSUE**

- Type: `Feature`, `Server` 
- Detail: 통계 기능 구현

### **TODO**

- [x] 통계 입력 로직 짜기
- [x] 통계 입력 기능 데이터 관련 DDL 구현
- [x] 트랜잭션 처리 및 예외 처리
