### ISSUE TITLE
[📍 Task Card - Server] 법안 발의문 리스트 조회

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#22]
### **ISSUE**

- Type: `Feature`, `Server`
- Detail: 법안 발의문 리스트 조회

### **TODO**

- [x] sortby - 최신순, 마감임박순, 찬성순, 반대순
- [x] search - 검색 
- [x] closed - 마감여부
- [x] page - 페이지당 게시물 개수
- [ ] 최적화 - 페이지네이션 소요 시간 최소화 -> advanced로 구현할 예정
