### ISSUE TITLE
[📍 Task Card - Client] 법안 발의문 상세 페이지 관련 컴포넌트 구현 (1) - 기본구조 및 댓글

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#5]
### **ISSUE**

- Type: `Feature`, `Client` 
- Detail: 법안 발의문 상세 페이지 관련 컴포넌트 구현

### **TODO**

- [x] 법안 발의문 상세 페이지 정보 불러오기 구현
- [x] 법안 발의문 삭제 구현
- [x] 댓글 컴포넌트 구현
- [x] 상태 관리 구현
