### ISSUE TITLE
[📍 Task Card - Server] 투표 현황 이메일 전송 기능 - ADVANCED

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#50]
### **ISSUE**

- Type: `Feature`, `Server` 
- Detail: 투표 현황 이메일 전송 기능

### **TODO**

- [x] 발의문 마감일에 투표율, 찬성율, 반대율 등 투표 현황 리포트 이메일로 전송
- [x] node-mailer로 이메일 전송 기능 구현
- [x] 투표 현황 페이지 (클라이언트 페이지) 캡쳐하여 메일로 보내기 구현
