### ISSUE TITLE
[📍 Task Card - Server] 실시간 댓글 알림 기능 - ADVANCED

### ISSUE THREAD

**Issue by soominna** [oxopolitics-internship-for-codestates/BePol#51]
### **ISSUE**

- Type: `Feature`
- Detail: 로그인한 유저가 쓴 글에 새로운 댓글이 달렸을 때 실시간으로 알림 전송

### **TODO**

- [x] socket 서버 연결
- [x] comment db 업데이트시 이벤트 발생
- [x] 헤더에 알림 아이콘 추가(클라이언트)
- [x] 알림 모달 만들어서 띄우기(클라이언트)
- [x] 클라이언트 socket 객체/알림 내역 -> redux 이용해 전역으로 저장
