### ISSUE TITLE
[📍 Task Card - Client] 메인페이지 관련 컴포넌트 구현 (1)

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#6]
### **ISSUE**

- Type: `Feature`, `Client`
- Detail: 메인페이지 관련 컴포넌트 구현

### **TODO**

- [x] 메인페이지 기본 구조 구현
- [x] 메인페이지 스타일 적용
- [x] 상태 관리 구현
