### ISSUE TITLE
[📍 Task Card - Client] 메인페이지 관련 컴포넌트 구현 (2)

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#7]
### **ISSUE**

- Type: `Feature`, `Client`
- Detail: 메인페이지 관련 컴포넌트 구현

### **TODO**

- [x] TOP3 관련 카드 컴포넌트 구현
- [x] 목록 관련 카드 컴포넌트 구현
- [x] 상태 관리 구현
- [x] Top3 게시글 서버와 연결
- [x] 목록 카드 게시글 서버와 연결
- [x] grid 스타일 적용
