### ISSUE TITLE
[📍 Task Card - Client] 법안 발의문 상세 페이지 관련 컴포넌트 구현 (2) - 통계

### ISSUE THREAD

**Issue by dltmddus1998** [oxopolitics-internship-for-codestates/BePol#8]
### **ISSUE**

- Type: `Feature`, `Client` 
- Detail: 법안 발의문 상세 페이지 관련 컴포넌트 구현

### **TODO**

- [x] 법안 발의문 통계 구현
- [x] 법안 발의문 통계 컴포넌트 구현
- [x] 상태 관리 구현
